### ISSUE TITLE
一些建议翻译的mod

### ISSUE THREAD

**Issue by yuanze31** [tinygrox/KSP_Chinese_Patches#1]
[x] Science! Continued https://github.com/linuxgurugamer/KSP-X-Science
AmpYear https://github.com/JPLRepo/AmpYear
Station Science Continued https://github.com/tomforwood/StationScience

**Comment by tinygrox** [comment]
@yuanze31 
**[x] Science! Continued** 涉及到代码修改，建议关注另一个项目 https://github.com/tinygrox/KSPHarmonyPatches
需要安装 [Harmony](https://github.com/KSPModdingLibs/HarmonyKSP)，不过这个项目还在实践中，未来很可能要重构，所以目前还没发布，还是得等等 😄 
**AmpYear** 下个版本就更新
**Station Science Continued** 这个目前没精力做了，文本也太多了 🥲 你们可以帮忙多宣传宣传这个翻译项目，让更多的人参与进来一起协助汉化。
