### ISSUE TITLE
可以把ResearchBodies的汉化添加到这里吗

### ISSUE THREAD

**Issue by zhangyuesai** [tinygrox/KSP_Chinese_Patches#15]
你好，我从KSP forum注意到你一年前就为ResearchBodies做了汉化并提交了pull request，但至今没有被merge。（可能是原作者已经不活跃了？）所以可以请你把汉化添加到这里吗？

另外，我找到这里是因为我刚刚自己做完了ResearchBodies的汉化，准备提交给原作者时才发现你已经做过了（然后又发现你就是Chinese Mod Patches的维护者）。简直欲哭无泪……附上我做的汉化版本 [Localization.cfg.txt](https://github.com/tinygrox/KSP_Chinese_Patches/files/13875223/Localization.cfg.txt) 。如果有兴趣的话也可以各取所长之处，做一个更好的翻译。不过我感觉你的翻译确实更准确清晰自然，我似乎完全是白翻译了，再次欲哭无泪……

最后还是要谢谢你的Chinese Mod Patches！

**Comment by tinygrox** [comment]
你不说我都忘了这个了，这周找个时间就更进去，或者你也可以 pull 个 request 过来我直接合并。

**Comment by tinygrox** [comment]
0.8.0 已更新
