### ISSUE TITLE
安装mod导致游戏内原版部件（中继天线，折叠梯子）没有收起放下选项，安装部件初始展开

### ISSUE THREAD

**Issue by timestar10086** [tinygrox/KSP_Chinese_Patches#53]
游戏版本1.12.5
mod通过ckan安装

**Comment by tinygrox** [comment]
问题已复现。
已于 [1.6.0](https://github.com/tinygrox/KSP_Chinese_Patches/releases/tag/v1.6.0) 修复。 
非常感谢 😃

**Comment by timestar10086** [comment]
👍👍👍👍👍👍
